import type { Metadata } from 'next';
import '../styles/globalStyle.scss';
import ProviderWrapper from '@/components/Provider/ProviderWrapper';

export const metadata: Metadata = {
  title: 'My Next App',
  description: 'Generated by create next app'
};

// ================================ ROOT LAYOUT =============================== //

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ProviderWrapper>{children}</ProviderWrapper>
      </body>
    </html>
  );
}
